name: Build APP for Android
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_android:
    name: Build Android version
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set build number
        run: echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter build apk --target-platform android-arm64 --build-number ${{ env.BUILD_NUMBER }}

      - uses: actions/upload-artifact@v3
        name: Upload Android APK
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/upload-artifact@v3
        name: Upload pubspec.lock
        with:
          name: pubspec.lock
          path: pubspec.lock
